### ISSUE TITLE
How do I build your modules?

### ISSUE THREAD

**Issue by Cordoha** [Djack13/VCV_Csound#3]
Cloned the repo, CD into it...

~/.Rack/plugins/CSound$ make
Makefile:12: ../../plugin.mk: No such file or directory
make: *** No rule to make target '../../plugin.mk'.  Stop.

I tried doing it the usual way as well, but no go.
I've installed CSound from the repos.

**Comment by Djack13** [comment]
Hi,
it is not ~/.Rack/plugins/CSound$
See my readme file
""Then cd to /Rack/plugins/VCV_Csound and compile with make""

To compile you can use the Rack sdk
or if using version 0.6.1 start with rack - d flag (d is for dev)

(if you start rack (without -d flag) you start the release version of rack, in that case the plugins are located in /.Rack )

**Comment by Cordoha** [comment]
Right, I got confused with this new Rack build. Thank you.
I'm now building in ~/Rack/plugins. Then placing in ~./Rack/plugins. Just realized if I do that, I guess they're building for the development version of Rack, but moved to the release. Hopefully that's okay. It may not be since I am getting errors with your plugins.

Not sure if there's an error with the plugin, or with rack. Here's the output: 

I'm in Ubuntu 18.04.

0dBFS level = 32768.0
--Csound version 6.10 (double samples) 2018-01-27 
[commit: none]
libsndfile-1.0.28
backtrace() returned 19 addresses
/usr/lib/libcsound64.so.6.0(+0x3f7e3) [0x7f618c0107e3]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f619466df20]
/usr/lib/libcsound64.so.6.0(+0x258014) [0x7f618c229014]
/usr/lib/libcsound64.so.6.0(+0x272601) [0x7f618c243601]
/usr/lib/libcsound64.so.6.0(+0x26ee34) [0x7f618c23fe34]
/usr/lib/libcsound64.so.6.0(+0x26ee82) [0x7f618c23fe82]
/usr/lib/libcsound64.so.6.0(csoundParseOrc+0x2d7) [0x7f618c24b6b7]
/usr/lib/libcsound64.so.6.0(+0x27a087) [0x7f618c24b087]
/usr/lib/libcsound64.so.6.0(csoundCompileArgs+0x1b0) [0x7f618c1763f0]
/usr/lib/libcsound64.so.6.0(csoundCompile+0x9) [0x7f618c177309]
/home/justin/.Rack/plugins/CSound/plugin.so(_ZN9MidiVCO10C1Ev+0x69f) [0x7f618c55e7cf]
/home/justin/.Rack/plugins/CSound/plugin.so(_ZZN4rack5Model6createI9MidiVCO1015MidiVCO10WidgetJNS_8ModelTagEEEEPS0_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_SB_DpT1_EN6TModel18createModuleWidgetEv+0x1c) [0x7f618c55f4a6]
./Rack(_ZTv0_n216_N4rack9ModelItem8onActionERNS_11EventActionE+0x26) [0x561a51e01c99]
./Rack(_ZTv0_n200_N4rack15BrowserListItem10onDragDropERNS_13EventDragDropE+0x59) [0x561a51e02081]
./Rack(_ZN4rack19mouseButtonCallbackEP10GLFWwindowiii+0xd7) [0x561a51dd6382]
./Rack(_ZN4rack9windowRunEv+0xe8) [0x561a51dd6acb]
./Rack(main+0x35e) [0x561a51d5d99e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6194650b97]
./Rack(_start+0x2a) [0x561a51d5f63a]
Csound tidy up: Segmentation fault
terminate called without an active exception
backtrace() returned 29 addresses
/usr/lib/libcsound64.so.6.0(+0x3f7e3) [0x7f618c0107e3]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f619466df20]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f619466de97]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f619466f801]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c8fb) [0x7f61950628fb]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d3a) [0x7f6195068d3a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d95) [0x7f6195068d95]
./Rack(_ZN4rack8VIPMutexD1Ev+0) [0x561a51db0884]
/lib/x86_64-linux-gnu/libc.so.6(+0x43041) [0x7f6194672041]
/lib/x86_64-linux-gnu/libc.so.6(+0x4313a) [0x7f619467213a]
/usr/lib/libcsound64.so.6.0(+0x3f8c8) [0x7f618c0108c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f619466df20]
/usr/lib/libcsound64.so.6.0(+0x258014) [0x7f618c229014]
/usr/lib/libcsound64.so.6.0(+0x272601) [0x7f618c243601]
/usr/lib/libcsound64.so.6.0(+0x26ee34) [0x7f618c23fe34]
/usr/lib/libcsound64.so.6.0(+0x26ee82) [0x7f618c23fe82]
/usr/lib/libcsound64.so.6.0(csoundParseOrc+0x2d7) [0x7f618c24b6b7]
/usr/lib/libcsound64.so.6.0(+0x27a087) [0x7f618c24b087]
/usr/lib/libcsound64.so.6.0(csoundCompileArgs+0x1b0) [0x7f618c1763f0]
/usr/lib/libcsound64.so.6.0(csoundCompile+0x9) [0x7f618c177309]
/home/justin/.Rack/plugins/CSound/plugin.so(_ZN9MidiVCO10C1Ev+0x69f) [0x7f618c55e7cf]
/home/justin/.Rack/plugins/CSound/plugin.so(_ZZN4rack5Model6createI9MidiVCO1015MidiVCO10WidgetJNS_8ModelTagEEEEPS0_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_SB_DpT1_EN6TModel18createModuleWidgetEv+0x1c) [0x7f618c55f4a6]
./Rack(_ZTv0_n216_N4rack9ModelItem8onActionERNS_11EventActionE+0x26) [0x561a51e01c99]
./Rack(_ZTv0_n200_N4rack15BrowserListItem10onDragDropERNS_13EventDragDropE+0x59) [0x561a51e02081]
./Rack(_ZN4rack19mouseButtonCallbackEP10GLFWwindowiii+0xd7) [0x561a51dd6382]
./Rack(_ZN4rack9windowRunEv+0xe8) [0x561a51dd6acb]
./Rack(main+0x35e) [0x561a51d5d99e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6194650b97]
./Rack(_start+0x2a) [0x561a51d5f63a]
Csound tidy up: Aborted
terminate called recursively
backtrace() returned 39 addresses
/usr/lib/libcsound64.so.6.0(+0x3f7e3) [0x7f618c0107e3]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f619466df20]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f619466de97]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f619466f801]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x94f9a) [0x7f619506af9a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d3a) [0x7f6195068d3a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d95) [0x7f6195068d95]
./Rack(_ZN4rack8VIPMutexD1Ev+0) [0x561a51db0884]
/lib/x86_64-linux-gnu/libc.so.6(+0x43041) [0x7f6194672041]
/lib/x86_64-linux-gnu/libc.so.6(+0x4313a) [0x7f619467213a]
/usr/lib/libcsound64.so.6.0(+0x3f8c8) [0x7f618c0108c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f619466df20]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f619466de97]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f619466f801]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c8fb) [0x7f61950628fb]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d3a) [0x7f6195068d3a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d95) [0x7f6195068d95]
./Rack(_ZN4rack8VIPMutexD1Ev+0) [0x561a51db0884]
/lib/x86_64-linux-gnu/libc.so.6(+0x43041) [0x7f6194672041]
/lib/x86_64-linux-gnu/libc.so.6(+0x4313a) [0x7f619467213a]
/usr/lib/libcsound64.so.6.0(+0x3f8c8) [0x7f618c0108c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f619466df20]
/usr/lib/libcsound64.so.6.0(+0x258014) [0x7f618c229014]
/usr/lib/libcsound64.so.6.0(+0x272601) [0x7f618c243601]
/usr/lib/libcsound64.so.6.0(+0x26ee34) [0x7f618c23fe34]
/usr/lib/libcsound64.so.6.0(+0x26ee82) [0x7f618c23fe82]
/usr/lib/libcsound64.so.6.0(csoundParseOrc+0x2d7) [0x7f618c24b6b7]
/usr/lib/libcsound64.so.6.0(+0x27a087) [0x7f618c24b087]
/usr/lib/libcsound64.so.6.0(csoundCompileArgs+0x1b0) [0x7f618c1763f0]
/usr/lib/libcsound64.so.6.0(csoundCompile+0x9) [0x7f618c177309]
/home/justin/.Rack/plugins/CSound/plugin.so(_ZN9MidiVCO10C1Ev+0x69f) [0x7f618c55e7cf]
/home/justin/.Rack/plugins/CSound/plugin.so(_ZZN4rack5Model6createI9MidiVCO1015MidiVCO10WidgetJNS_8ModelTagEEEEPS0_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_SB_DpT1_EN6TModel18createModuleWidgetEv+0x1c) [0x7f618c55f4a6]
./Rack(_ZTv0_n216_N4rack9ModelItem8onActionERNS_11EventActionE+0x26) [0x561a51e01c99]
./Rack(_ZTv0_n200_N4rack15BrowserListItem10onDragDropERNS_13EventDragDropE+0x59) [0x561a51e02081]
./Rack(_ZN4rack19mouseButtonCallbackEP10GLFWwindowiii+0xd7) [0x561a51dd6382]
./Rack(_ZN4rack9windowRunEv+0xe8) [0x561a51dd6acb]
./Rack(main+0x35e) [0x561a51d5d99e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6194650b97]
./Rack(_start+0x2a) [0x561a51d5f63a]
Csound tidy up: Aborted
backtrace() returned 6 addresses
/usr/lib/libcsound64.so.6.0(+0x3f7e3) [0x7f618c0107e3]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f619466df20]
./Rack(+0x1d2105) [0x561a51daf105]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbe733) [0x7f6195094733]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f61969266db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f619475088f]
Csound tidy up: Segmentation fault

**Comment by Djack13** [comment]
I can just note the differences with my system:

VCVRack v0.6.1, Csound v6.11 and VCV Rack modules are compiled and tested......

Have compiled Csound version 6.11 (6.10 have a bug with strings channels)

Csound should be installed in the default location, i.e, includes files should be located in /user/local/include/csound while the Csound library itself should be located in /user/local/lib.

Your csound is version 6.10 and located in /usr/lib
Did you get warnings during compilation?
