### ISSUE TITLE
Getting error when compiling in Ubuntu machine

### ISSUE THREAD

**Issue by 573** [Djack13/VCV_Csound#4]
Followed the steps given in README but the make step ends:

> rack_plugins_1      | ++ make
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -DSLUG=VCV_Csound -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Yfx.cpp.o src/Yfx.cpp
rack_plugins_1      | src/Yfx.cpp: In member function 'void Yfx::csoundCession()':
rack_plugins_1      | src/Yfx.cpp:56:76: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
rack_plugins_1      |          notReady = csound->Compile(assetPlugin(plugin, "csd/Yfx.csd").c_str(), (char *) sr_override.c_str());
rack_plugins_1      |                                                                             ^
rack_plugins_1      | In file included from src/Yfx.cpp:3:0:
rack_plugins_1      | /usr/include/csound/csound.hpp:219:15: note:   initializing argument 1 of 'virtual int Csound::Compile(char*, char*)'
rack_plugins_1      |    virtual int Compile(char *orcName, char *scoName)
rack_plugins_1      |                ^
rack_plugins_1      | make: *** [build/src/Yfx.cpp.o] Error 1
rack_plugins_1      | ../../compile.mk:64: recipe for target 'build/src/Yfx.cpp.o' failed

I have libcsnd-dev from ubuntu 16.04 (xenial) installed in my setup.

Does it make sense to " try adding this line to Custom.cmake:

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpermissive")" ? (http://csound.1045644.n5.nabble.com/Csnd-trouble-compiling-6-11-on-Ubuntu-tp5762021p5762036.html, https://travis-ci.org/csound/csound)

**Comment by 573** [comment]
I was able to get plugin.so by adding `-fpermissive` to plugin.mk in RACK_DIR (line where it then says `FLAGS += -fPIC -fpermissive`).
Maybe there is a better more modular solution IDK.

**Comment by Djack13** [comment]
Have removed (char *) from csound->compile(.......) call.
In all modules, for my system it make no difference!  I can't test on other os.
